target_repository:
  HTTPS: https://github.com/neptune-ai/neptune-client
  # OPTIONAL, checkout a particular branch or a tag
  checkout: aw/adjust_e2e_tests
  # OPTIONAL, define installing package extras
  install_extras: all
  # OPTIONAL, install additional requirements from a file
  requirements_file: requirements.txt
  # copy some  test from the target repository
  copy_tests:
    - e2e_tests/integrations/

contact:
  slack:
    - Aleksander Wojnarowicz
  email: [aleksander.wojnarowicz@neptune.ai, backend@neptune.ai]

# OPTIONAL, if any installation require some env. variables
env:
  NEPTUNE_API_TOKEN: ANONYMOUS
  NEPTUNE_LIGHTNING_ECOSYSTEM_CI_PROJECT: common/lightning-ecosystem-ci

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/Lightning-AI/lightning.git
    checkout: release/1.5.x
    # install_extras: all
  - name: Cython
    checkout: 0.29.24

testing:
  dirs:
    - e2e_tests
  # OPTIONAL, additional pytest arguments
  pytest_args: -m lightning

runtimes:
  - {os: "ubuntu-20.04", python: "3.7"}
#  - {os: "macOS-10.15", python: "3.7"}
#  - {os: "windows-2019", python: "3.7"}
