target_repository:
  HTTPS: https://github.com/neptune-ai/neptune-client
  # OPTIONAL, checkout a particular branch or a tag
  checkout: aw/adjust_e2e_tests
  # OPTIONAL, define installing package extras
  install_extras: all
  # OPTIONAL, install additional requirements from a file
  requirements_file: requirements.txt
  # copy some  test from the target repository
  copy_tests:
    - e2e_tests/integrations/__init__.py
    - e2e_tests/integrations/test_lightning.py
    - e2e_tests/conftest.py
    - e2e_tests/base.py
    - e2e_tests/utils.py
    - e2e_tests/exceptions.py
    - e2e_tests/pytest.ini

contact:
  slack:
    - Aleksander Wojnarowicz
  email: [aleksander.wojnarowicz@neptune.ai, backend@neptune.ai]

before_install:
  - pip install Faker==15.0.0
  - pip install pytorch-lightning
  - pip install neptune-client==0.15.0

# OPTIONAL, if any installation require some env. variables
env:
  PACKAGE_NAME: pytorch
  NEPTUNE_API_TOKEN: ANONYMOUS
  NEPTUNE_LIGHTNING_ECOSYSTEM_CI_PROJECT: common/lightning-ecosystem-ci

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/Lightning-AI/lightning.git
    checkout: release/pytorch
    # install_extras: all

testing:
  dirs:
    - e2e_tests
  # OPTIONAL, additional pytest arguments
  pytest_args: -m lightning

runtimes:
  - {os: "ubuntu-20.04", python: "3.7"}
#  - {os: "macOS-10.15", python: "3.7"}
#  - {os: "windows-2019", python: "3.7"}
