target_repository:
  HTTPS: https://github.com/PyTorchLightning/metrics.git
  # OPTIONAL, for some protected repository
  # username: my-nick
  # OPTIONAL, paired with the username
  # password: dont-tell-anyone
  # OPTIONAL, overrides the user/pass
  # token: authentication-token
  # OPTIONAL, checkout a particular branch or a tag
  checkout: master
  # OPTIONAL, define installing package extras
  install_extras: all
  # OPTIONAL, install additional requirements
  # install_file: requirements.txt
  # OPTIONAL, copy some  test from the target repository
  copy_tests:
    - integrations
    - tests/__init__.py
    - tests/helpers

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: release/1.5.x
    install_extras: all

testing:
  dirs:
    - .
  pytest_args: {}
