target_repository:
  HTTPS: https://github.com/PyTorchLightning/metrics.git
  checkout: master
  install_extras: all
  install_file: requirements.txt
  copy_tests:
    - integrations

dependencies:
  - name: PL
    HHTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: release/1.5.x
    install_extras: all

testing:
  dirs:
    - .
