name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push: {}
  pull_request:
    branches: [main]
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]  # TODO: , macOS-10.15, windows-2019
        python-version: [3.8]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: echo "::set-output name=period::$(python -c 'import time ; days = time.time() / 60 / 60 / 24 ; print(int(days / 7))' 2>&1)"
      if: matrix.requires == 'latest'
      id: times

    # Note: This uses an internal pip API and may not always work
    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
    - name: Get pip cache
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-py${{ matrix.python-version }}-td${{ steps.times.outputs.period }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-py${{ matrix.python-version }}-td${{ steps.times.outputs.period }}-pip-

    - name: Prepare scripts
      run: |
        pip install -q -r requirements.txt
        python .actions/assistant.py prepare_env --config_file=.actions/config.yaml > prepare_env.sh
        cat prepare_env.sh
      shell: bash

    - run: echo "::set-output name=args::$(python .actions/assistant.py specify_tests --config_file=.actions/config.yaml 2>&1)"
      id: spec_tests

    - name: Installing
      run: |
        sudo apt install -q tree
        bash prepare_env.sh
        tree .
      shell: bash

    - name: Testing
      run: |
        echo ${{ steps.spec_tests.outputs.args }}
        coverage run -m pytest ${{ steps.spec_tests.outputs.args }} -v --junitxml=junit/test-results-${{ runner.os }}-${{ matrix.python-version }}.xml

    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ runner.os }}-${{ matrix.python-version }}
        path: junit/test-results-${{ runner.os }}-${{ matrix.python-version }}.xml
      if: failure()

    # TODO: report failure to Slack

    - name: Statistics
      if: success()
      run: |
        coverage report
        coverage xml
